### ISSUE TITLE
Doble poeng i enkelte perioder for økt aktivitet

### ISSUE THREAD

**Issue by fre4k** [hswno/kofradia#10]
Hei!

 Jeg satt å tenkte litt på hvordan vi kunne holde den aktiviteten som vi har nå oppe, og jeg kom frem til en ide.

 Hva synes dere om å kjøre enkelte dager (helger) hvor vi har doble poeng på Kriminalitet, utpressing, gta og lotto?

 Jeg tror selv dette vil øke aktiviteten blant spillerne. :-)

https://kofradia.no/crewstuff/trac/ticket/510

Sjekk trac for kommentarer

**Comment by Dreamfreeze** [comment]
Synes dette er tull. Uansett når, hvor og hva. Kofradia trenger ikke viderefølge en mye vil ha mer-filosofi. Det er også enkelt nok å ranke opp for lavrankede, så de behøver ikke noe slik. Andre som har noen formening om dette?

**Comment by actanon** [comment]
Kan bare droppe det ja

**Comment by Niirve** [comment]
Enig. Ikke nødvendig.

**Comment by Kuzat** [comment]
Tar å lukker denne ettersom det ser ut som folk er enige om at den ikke er nødvendig.
