### ISSUE TITLE
Drapsstatistikk

### ISSUE THREAD

**Issue by Superial** [hswno/kofradia#111]
Dersom en spiller dør av skadene en annen spiller påførte ham telles ikke det opp på statistikksiden. 

Ref: https://kofradia.no/support/?a=show&su_id=10059

**Comment by Dreamfreeze** [comment]
Saken her er at spilleren har drept 18 spillere og i tillegg har én blitt drept av skader påført tidligere. På statistikksiden viser det 18 drepte spillere, mens på profilen står det sammenlagt 19 drept.

Jeg ser to løsninger.
Løsning 1: Sørge for at spillere med flest drap på statistikken slår sammen drap som kommer av skader påført tidligere.
Løsning 2: Splitte drap vist på profilen til å si at 18 har blitt drept og 1 drept av skader påført tidligere.

**Comment by actanon** [comment]
Jeg synes løsning 2

**Comment by Mishapen** [comment]
Mener løsning to kan bli litt rotete, om du skal ramse opp spillere drept, spillere dødd av skade påført og spillere skadet. Jeg tenker det er greit å heller dele det opp på statistikksiden, og ha "spillere drept" som en kolonne og "spillere drept av skader påført tidligere" (evt formulert annerledes) på statistikksiden.

**Comment by actanon** [comment]
Jo, du har nok rett i det når jeg tenker meg om.

**Comment by Dreamfreeze** [comment]
Ved nærmere ettertanke, tror jeg ikke Henrik overså dette i utgangspunktet. Jeg tror det hadde en hensikt, som nemlig er å gjøre det vanskeligere for folk å vite hvem som dreper og gjøre vitner mer verdifulle. Så kanskje er det bedre med løsning 1, slik at vi er konsekvente mellom profil og statistikk.

Skulle vi derimot gå for løsning 2, tenker jeg at vi fint kan gjøre det uten at det blir rotete. Setningen kan kortes ned betraktelig. Det vi ser er at det ikke er stor forskjell med nåværende versjon, og den nye og nedkortede versjonen.
Nå står det:
Utført 100 angrep, hvorav 10 spillere har blitt drept, og 50 spillere har blitt skadet.
Den nye versjonen som også er kortet ned:
Utført 100 angrep: 10 spillere drept, 2 spillere drept av tidligere skader og 50 spillere skadet.

Å sette opp en egen kolonne på statistikksiden tror jeg blir rotete. Den har ingen innvirkning på flest drap og er dessuten nesten ubrukelig ettersom slike drap er sjeldne og de aller fleste vil ha 0 på telleren. Det får meg til å tenke løsning 1 nok en gang.

**Comment by Mishapen** [comment]
Da mener jeg det bør stå som det er. Veldig godt resonnert, Ole.
