### ISSUE TITLE
Forslag: Senking av poengkrav for nye broderskap

### ISSUE THREAD

**Issue by actanon** [hswno/kofradia#126]
Jeg foreslår å senke rankkravene for nye broderskap for å gjøre det enklere for nye medlemmer å danne broderskap og etablere seg på spillet. Gjerne så mye som en halvering av kravet.

https://kofradia.no/forum/topic?id=93724&replyid=1622660

> Navn: Senking av rankkrav for nye broderskap
> Beskrivelse: Vi har nylig sett at broderskapet Royal Empire har bygget seg opp. Velmine har samlet sammen en haug med medlemmer som ikke hadde så mange kontakter på spillet, og gitt de en sjanse til å bygge seg opp. Noen har misbrukt sjansen ved å prøve å svindle/drepe, mens andre nok har blitt kjent med folk og bygget seg opp verdier. Det viser jo seg at det ofte er de spillerne som kjenner noen fra før som lykkes her, siden de kan få litt hjelp, tips, verdier og noen å samarbeide med. Det er nok litt gøyere å spille Kofradia når man er i et broderskap og kan samarbeide med noen mot et felles mål.
> 
> Hvorfor har Royal Empire gitt sjansen til nye spillere, mens Memento og Revenge aldri eller sjelden gjør dette? Fordi Memento og Revenge ikke har et egoistisk behov for nye medlemmer ettersom de allerede har mange sterke spillere med ressurser, og fordi man ikke kan stole på alle. Derfor tar de to etablerte broderskapene helst inn folk de kjenner til fra før. Royal Empire derimot hadde vel et behov for nye spillere for å vinne rankekonken, men også for å ha noen som kan være med å bygge seg opp, som også Velmine - en erfaren Kofradia-spiller, men kanskje litt uten kontakter for tiden(?) - måtte gjøre på sin nye bruker.
> 
> Royal Empire har resultert i flere aktive medlemmer, som jo er det alle på Kofradia håper på. Nye medlemmer er det spillet virkelig trenger, alt annet kommer i andre rekke etter min mening. Dermed har Velmine (og andre som har styrt der, som feks Magnus) gjort en kjempejobb for Kofradia allerede. Det jeg håper på er at flere skal kunne lage nye broderskap og få med seg nye Kofradia-spillere, og sørge for at de holder seg aktive og bygger seg opp. Da kan de bli motiverte til å spille videre og kanskje verve venner. Broderskap-funksjonen ser jeg altså på som en potensiell kjempebra måte for å knytte til seg nye medlemmer.
> 
> Så til poenget. I lang tid har det vært mulig å lage nytt broderskap via broderskapkonkurranse uten reell konkurranse, bortsett fra rankkravet man må oppnå. Etter min erfaring er dette rankkravet ikke bare-bare. Nylig vant jeg og en del folk fra Memento-gjengen et broderskap, og vi var vel 6 erfarne spillere som ranket relativt aktivt. Vi var også avhengige av å få rankeoppdrag (og dermed klare pokeroppdrag i forkant ...) og ha noen å skyte på. Vi klarte det til slutt, men det var egentlig på hengende håret, og jeg syntes vi ranket ganske bra. Hvis en liten gjeng med uerfarne spillere - si 3-4 stk - prøver å vinne en familie blir det verre, spesielt uten mulighet for skyting. Jeg tror vi kan oppleve større vekst blant medlemmer hvis vi gjør det lettere å vinne et broderskap.
> 
> Det jeg altså ønsker er at vi senker antall poeng et broderskap må oppnå for å kunne vinne. Etter min erfaring ganske mye også, jeg vil foreslå noe sånt som en halvering av antall poeng. Det må være lett å skaffe seg et broderskap, og fordelene med å ha et broderskap (de finnes i stor grad!) må bli tydelige for nye medlemmer. Jeg er klar over at det ikke finnes konkurranser akkuat nå, men det er fordi ingen viste interesse for å opprette nye broderskap, som igjen kan vise til at det er vanskelig å vinne og drive et broderskap. Det viser også til liten aktivitet i det siste, men den er virkelig på vei opp nå, igjen, mye takket være bla. Velmine og Magnus etter min mening.

**Comment by Dreamfreeze** [comment]
Jeg tenker egentlig at 105 000 poeng fungerer bra, men samtidig er jeg enig i mange av punktene som blir fremmet i forslaget om å senke det. Kan fint se for meg et minstekrav mellom 50 000 og 75 000 poeng, men absolutt ikke noe lavere.

**Comment by Niirve** [comment]
Det er ikke noe problem å klare kravet som er nå. Jeg tror vi kom over 200% da vi vant forrige konkurranse. Jeg kan gå med på 75 000 poeng, men noe lavere burde det ikke være.

**Comment by daniehol** [comment]
Da foreslår jeg at vi endrer kravet til 75k.
