### ISSUE TITLE
Forslag: Senking av avgift for broderskap

### ISSUE THREAD

**Issue by actanon** [hswno/kofradia#127]
Jeg foreslår å senke avgiften for broderskap på flere måter for å gjøre det mer attraktivt og lettere å drive et broderskap. For å gjøre det mer rettferdig kan vi la sterke broderskap betale mer enn svake.

https://kofradia.no/forum/topic?id=93724&replyid=1622660

>Navn: Senking av avgift for broderskap
> Beskrivelse: Nye medlemmer vil også slite med penger. Avgiften er på 100 mill, kan rankes ned til 10, men det kan være vanskelig og mange vil gjerne ende opp på rundt 50 mill hver 10. dag i avgift, som kan virke demotiverende når medlemmene prøver å samle sammen penger gjennom renting og andre metoder. Her kan det gjøres flere ting. Man kan senke antall poeng man må ha for å ranke ned til 10 mill, man kan senke startavgiften, eller man kan muligens få til et progressivt skattesystem som gjør at avgiften bestemmes ut fra antall poeng broderskapet har, (med mulighet for å ranke ned avgiften som før) så de etablerte broderskapene fortsatt betaler mye, mens de nye familiene med mindre ressurser slipper billigere unna. 

> Jeg er klar over at forslag 2 går helt mot planen om å suge penger ut av spillet, men jeg synes ikke det er der vi skal få ut pengene. Pengene må suges ut fra de med alt for mye penger, altså de med flere milliarder, ikke de stakkars nyetablerte spillerne som bare eier noen millioner.

**Comment by Dreamfreeze** [comment]
Avgiften er i dag på 50 millioner (5 plasser) i tillegg til 5 millioner for hver ekstra plass (opptil 10 ekstra plasser), så dette forslaget har vel slått gjennom og er i drift.
