### ISSUE TITLE
Rettelser på informasjonssidene

### ISSUE THREAD

**Issue by KFJaguar** [hswno/kofradia#137]
Det har seg da slik at informasjonssidene til Kofradia ikke er blitt helt rettet siden overgangen fra StreetzMafia til Kofradia, og noen av forklaringene av funksjonene er misvisende.

https://kofradia.no/support/?a=show&su_id=10142

**Comment by Dreamfreeze** [comment]
Synes virkelig disse burde gjennomgås. Det har etter hvert samlet seg opp veldig mye feilinformasjon på sidene. Kanskje få noen med god kjennskap til funksjonene til å hjelpe til å lese gjennom og endre på?

**Comment by Dreamfreeze** [comment]
Jeg skrev om alle de sidene som jeg følte var nødvendig i slutten av 2015. Tenker at denne kan lukkes.
