### ISSUE TITLE
Forbedre infotekst ved registrering av bruker

### ISSUE THREAD

**Issue by henrist** [hswno/kofradia#143]
Teksten på registreringssiden er ganske kjedelig:

> Velkommen til Kofradia sine nettsider! Kofradia er et tekstbassert nettspill som handler om å utføre forskjellige funksjoner for å stige i gradene. I tillegg finnes det både forum og diverse annen informasjon på siden!
> 
> På denne siden oppretter du din bruker og spiller. Merk! Det er kun lov å ha én bruker. Har du allerede en bruker fra før har du ikke lov til å registrere ny bruker.

Denne bør friskes opp litt.
https://kofradia.no/registrer

**Comment by Dreamfreeze** [comment]
Velkommen til Kofradia! Kampen om broderskapet tar sted i Drammen hvor folket har tatt opp kampen for å etablere seg. Her handler det ikke bare om å ha mest penger eller være høyest rank, men å stå samlet for å etablere det sterkeste og mektigste broderskapet. Kanskje kan du være med å gjøre en forskjell? Lykke til!

Kort og greit. Bedre?

**Comment by actanon** [comment]
Ja, det kan vi bruke i stedet.

**Comment by Kuzat** [comment]
Her er koden som må forandres. Burde være lett å forandre.

https://github.com/hswno/kofradia/blob/dcd4157d68f2349b205479250a798edfde99c6ff/public/registrer.php#L380

Synes også @Dreamfreeze sitt forslag var bra.

**Comment by Dreamfreeze** [comment]
Nei, nå fikser jeg dette. Herre min hatt! Ingen andre tilbakemeldinger, og de som har sagt noe mener det er bra. It's going in the game.
