### ISSUE TITLE
For mange plasser i bomberom

### ISSUE THREAD

**Issue by KFJaguar** [hswno/kofradia#151]
Det ser ut til at det er litt for mange plasser i bomberommene, enn det som er nødvendig. Det er for øyeblikket 27 plasser totalt i Tilfulktsrommet, 51 plasser i Frihavnen og 26 plasser i Bragernes bomberom.

**Comment by Dreamfreeze** [comment]
Ettersom denne ikke er relatert #168 og virker løst, kan den lukkes?
