### ISSUE TITLE
Forslag: "Status"-funksjon i fengselet

### ISSUE THREAD

**Issue by actanon** [hswno/kofradia#166]
Jeg har et forslag som kommer etter mye frustrasjon grunnet misforståelser i forhold til fengselet. 

Problem: Ofte ønsker man ikke at andre skal bryte deg ut, fordi man for eksempel hjelper andre med fengselsoppdrag eller holder på med skyting og vil vite nøyaktig når man blir utbrutt. Utbryter har gjerne bare intensjon om å være grei, men så er utbryter heller den som ødelegger et forsøk på angrep, i et tenkt eksempel.

Løsning: Lag en mulighet for å legge til "melding" eller "status" i fengselet. Der kan man for eksempel skrive "ikke bryt meg ut - hjelper til med fengselsoppdrag" eller "skyter person X, bryt meg ut raskt om du vil ha X død!". En slik oppfordring som den siste kan gjerne være enda mer effektiv enn en dusør, og det er heller ikke alle som har mulighet til å betale for utbryting.

**Comment by Dreamfreeze** [comment]
Virker ikke som denne trenger å stå åpen når flere ikke ser poenget med den.
