### ISSUE TITLE
Bug: Bomberom og ledig plass

### ISSUE THREAD

**Issue by DSivertsen** [hswno/kofradia#168]
Det er nå kommet en bug i bomberommene. Bomberommene blir aldri fulle. Når det står det er 5 som sitter i bomberom og det er 8 ledig plasser i bomberommet. Når du da setter inn spillere i bomberom vil ikke ledig plasser synke. Statestikken vil derfor vise at det befinner seg 8 som sitter i bomberom og at det enda er 8 ledig plasser i bomberommet.

**Comment by Kuzat** [comment]
Denne burde være fikset nå
