### ISSUE TITLE
Global Antibot

### ISSUE THREAD

**Issue by Rudde** [hswno/kofradia#174]
Hei.

Er sikkert fler en meg som ikke er verdens største fan av antibots. Lurer på om vi heller kan ha en "Global" antibot fremfor en antibot for vær enkelt funksjon? Altså om jeg nettopp løser en antibot på kriminalitet, så er jeg helt sikkert ikke en bot når jeg gjør utpressing 5 sekunder senere og må løse en til? Eller hva?

**Comment by KFJaguar** [comment]
Er dette vanskelig å implementere eller er dette en generell forbedring vi kan få gjort uten særlig mye arbeid?

**Comment by Niirve** [comment]
Støttes. Det er veldig irriterende hvis de dukker opp veldig tett på hverandre på forskjellige funksjoner når man ranker.
