### ISSUE TITLE
Feil ved oppdrag

### ISSUE THREAD

**Issue by fre4k** [hswno/kofradia#18]
Det har seg slik at rankebonusen som en får klokken 21:00 hver dag teller på rankeoppdraget, og det blir jo litt feil. Siden den bonusen er ikke rank som en har fått mens en har holdt på med oppdraget.

---

https://kofradia.no/crewstuff/trac/ticket/553

**Comment by Dreamfreeze** [comment]
Se #200 for nøyere forklaring.
