### ISSUE TITLE
Opprettelse av foruminnlegg - javascriptfeil?

### ISSUE THREAD

**Issue by henrist** [hswno/kofradia#181]
Blir ikke sendt til det nye innlegget når man oppretter nytt innlegg. Kommer meldingsboks om at forumtråden ble opprettet uten at noe skjer.

**Comment by Dreamfreeze** [comment]
Dette er vel bare i crewforum?

**Comment by daniehol** [comment]
Dette er bare i crewforumet.

**Comment by Kuzat** [comment]
Fikset det ved å flytte Email klassen til namespace. Se commit ee9a7c314156adef1bcd3ac221e3adde4ed75b46 på php7.0 branchen

**Comment by daniehol** [comment]
Vi lar bugen være i php versjon 5.
