### ISSUE TITLE
Bomberom og oppdrag

### ISSUE THREAD

**Issue by fre4k** [hswno/kofradia#19]
At en ikke skal sitte i bomberom når en holder på med et oppdrag slik at en ikke kan feile på poker oppdraget også sette seg i bomberommet til tiden går ut. Også at en prøver å gjør oppdraget på nytt når tiden er ute.

---

https://kofradia.no/crewstuff/trac/ticket/554

**Comment by daniehol** [comment]
Forklart på en annen måte av Kuzat: Problemet er at man er i fengsel samtidig som man er i bomberom. Så da blir det ingen risiko når man gjør oppdrag i skytetiden.

**Comment by daniehol** [comment]
Løsning: Ikke kunne sette seg selv inn, men man kunne sette inn andre personer.
