### ISSUE TITLE
Visningsfeil av poeng under rankeoppdrag

### ISSUE THREAD

**Issue by Dreamfreeze** [hswno/kofradia#196]
Se her: http://puu.sh/lyCS2/521cd8eae6.png

På bildet ser man et rankeoppdrag hvor poengene man må oppnå viser forskjellig.
"Oppnå totalt 2 198 945 poeng" (beskrivelsen)
"Du må oppnå 2 198 801 poeng" (fremdriften) (samme som i headeren)

Poengene i beskrivelsen øker etter hvert som man ranker. Før man har startet oppdraget, vil den vise riktig, men så snart man har startet oppdraget og begynner å ranke, viser beskrivelsen feil.

Bildet viser at det allerede er ranket 144 poeng og at 256 poeng gjenstår. Tar man 144 poeng og legger sammen med fremdriften, så vil man få det samme som står i beskrivelsen.

Den enkleste løsningen jeg ser for dette, kan være at beskrivelsen forteller antallet poeng man må ranke, istedenfor å fortelle hvor mye man må oppnå. Da ville det stått "Du må ranke 400 poeng i løpet av 30 minutter". Viktig å være obs på at antall poeng man må ranke avhenger av rank, så det nytter ikke bare å skrive 400 poeng.

**Comment by Kuzat** [comment]
Jeg forslår at vi går for den enkle løsningen som @Dreamfreeze foreslo. 

Det er enkelt å endre. Vi tar bare denne linen
[$target = $this->up->data['up_points']+$params->get("points");](https://github.com/hswno/kofradia/blob/master/app/extra/class.oppdrag.php#L1485)
og skriver den om til
 $target = $params->get("points");

Da vil det i stedet for å vise totalt antall poeng bare vise akkurat så mange poeng du trenger for å klare oppdraget.
