### ISSUE TITLE
Feil med avstemninger

### ISSUE THREAD

**Issue by Dreamfreeze** [hswno/kofradia#197]
Det er to feil med avstemninger.

Den ene er at forummal ikke fungerer. Når man oppretter ny avstemning har man mulighet til å knytte en forumtråd til avstemningen som blir opprettet samtidig. Problemet er at tråden ikke blir opprettet sammen med avstemningen, slik det er meningen. Antakelig kan feilen rettes opp i dette området: https://github.com/hswno/kofradia/blob/3ed062696adfbe67c06e6ba50bb13243b9662c25/public/crew/avstemninger.php#L149

Den andre feilen dukker opp når man skal avgi stemme. Etter å ha avgitt stemme, kommer det "Din stemme ble ikke registrert.", men den blir likevel registrert. Feilen ligger trolig her: https://github.com/hswno/kofradia/blob/3ed062696adfbe67c06e6ba50bb13243b9662c25/app/src/Kofradia/Controller/Polls.php#L103

**Comment by actanon** [comment]
Bra dette endelig blir tatt.

**Comment by Kuzat** [comment]
Tror feilen med forummalen ligger i dette området. Klarer ikke helt se hva som er feil.
https://github.com/hswno/kofradia/blob/dcd4157d68f2349b205479250a798edfde99c6ff/public/themes/sm/default.php#L285

**Comment by daniehol** [comment]
Et bedre stalltips vil muligens være å ta en titt i avstemnings klassen;
https://github.com/hswno/kofradia/blob/dcd4157d68f2349b205479250a798edfde99c6ff/public/crew/avstemninger.php#L149
