### ISSUE TITLE
Feil med bonus og rankeoppdrag

### ISSUE THREAD

**Issue by Dreamfreeze** [hswno/kofradia#200]
Det kom inn en henvedelse om feil ved vervebonus under rankeoppdrag. Crewet kan se den her: https://kofradia.no/support/?a=show&su_id=10254

Feilen er at bonus som mottas av vervebonus teller på rankeoppdraget. I verste fall er disse poengene de som fullfører oppdraget og spilleren får hendelsen "Oppdraget «Ranking» ble utført vellykket!" uten å få noen bekreftelse på at penger, poeng og kuler ble mottatt slik hendelsen vanligvis forteller. Problemet er da at det blir usikkert på om man faktisk mottok premien for vellykket oppdrag. Dersom poengene for oppdraget faktisk ble mottatt, så teller ikke disse på dagens ranker-statistikken som gir bonus klokken 21.

Et liknende tilfelle oppstår hvis en spiller mottar poeng fra bonusen klokken 21 under rankeoppdrag. Se: http://puu.sh/lILOf/7703e9cd4f.png (hentet fra: https://kofradia.no/min_side?up_id=41699&a=log&f16=&f20= 19. november 2015)

**Comment by Kuzat** [comment]
Den enkleste vil være å gjøre at vervebonusen og klokken 21 bonusen ikke teller på rankeoppdraget.

**Comment by daniehol** [comment]
Støtter forslaget ditt @Kuzat
