### ISSUE TITLE
Ledelsen er uinteressert

### ISSUE THREAD

**Issue by Dreamfreeze** [hswno/kofradia#205]
Spillet har nylig tatt opp litt aktivitet igjen, men Ledelsen viser ingen interesse. Noe er ikke slik som det skal. Se bilde.
https://i.imgur.com/G2QxjUA.png

Er det på tide med noen endringer for å få fikset dette? Forslag kan være å bytte dem ut.

Innvendinger? Kommentér under.

**Comment by actanon** [comment]
Vega har vel basically sagt at han godt kan ryke.
