### ISSUE TITLE
Forvirring i overføringslogg

### ISSUE THREAD

**Issue by Dreamfreeze** [hswno/kofradia#208]
Se support: https://kofradia.no/support/?a=show&su_id=10292

Loggen henter info etter overføringsgebyret til avsender, men ikke etter gebyret til mottaker. Det kan være forvirrende, og burde oppklares.

Vil gå ut ifra at feilen kan rettes opp ved å endre info[4] (referert til linje 825) her:
https://github.com/hswno/kofradia/blob/dcd4157d68f2349b205479250a798edfde99c6ff/app/pages/banken.php#L868
Se også linje 872 rett nedenfor der.

Jeg forstår at mottaker skal få beskjed om hvor mye banken mottar (altså før gebyren blir trukket i hans bank), men det ville vært mer oversiktlig om mottaker får logg om det som faktisk kommer inn i hans bank. Jeg tenker det er viktigere å opplyse om det som kom inn på konto, fremfor å opplyse om hvilket beløp banken trakk gebyr fra.

**Comment by actanon** [comment]
Støtter dette! Fix!

**Comment by Mishapen** [comment]
Jeg er også enig i dette, husker jeg hang meg opp i det for mange år siden. Positiv endring.
