### ISSUE TITLE
20% vervebonus i desember

### ISSUE THREAD

**Issue by Kuzat** [hswno/kofradia#218]
https://github.com/hswno/kofradia/blob/8bf6d7992b566dc2a5fb006db797770a635875ea/app/scheduler/vervebonus.php#L15

Koden funker bare for desember 2012. Er dette noe som skal fungere hver desember eller skal det bare fjernes?

**Comment by Dreamfreeze** [comment]
Hver desember, imo.

**Comment by actanon** [comment]
Synes også vi kan satse på desember, det er en måned vi ofte er sterke på faktisk :O
