### ISSUE TITLE
Forlate bomberom er langtekkelig

### ISSUE THREAD

**Issue by Dreamfreeze** [hswno/kofradia#220]
Slik ser det ut om man skal forlate bomberom i dag: https://i.imgur.com/eICq3hp.gifv

Prosessen er lengre enn den trenger å være. Som vist, må man laste **fire sider** før man omsider har forlatt bomberommet. Det er iallfall to mer enn nødvendig, mener jeg. 

Ideelt sett kunne jeg sett for meg at man f.eks. trykket "lotto" deretter "forlat bomberom" og så var man ute, fremfor at man må trykke seg frem til å bli sendt til firmaet, velge å forlate, og deretter bekrefte. Om bekreftelse er så pass vitkig, kan man i det aller minste kutte steget hvor man sendes til firmaet. Det er ikke noen stor game changer, men det vil gjøre livet for mange på Kofradia mye enklere.

PS: På samme måte er det en smule langtekkelig å sette seg inn, men det får bli en annen sak, og dessuten må det bli etter en løsning på bydeler som nevnt i kommentaren til Henrik i #147.

**Comment by actanon** [comment]
Veldig enig her, hadde vært flott med en kjapp link.

**Comment by Niirve** [comment]
Det hadde egentlig vært greit om det hadde dukket opp som en knapp for eksempel i headeren. Trykk på knappen i headeren, bli tatt til EN side hvor du bekrefter med å trykke forlat igjen.

**Comment by Dreamfreeze** [comment]
Du tenker noe liknende i headeren som dukker opp ved oppdrag?

**Comment by Niirve** [comment]
Ja, tror det ville passet med en liten boks med en "Forlat bomberom" knapp der. Når du da klikker på den så blir du tatt direkte til en bekreftelse på å forlate bomberommet. Da går vi fra alt for mange klikk, ned til bare to.

**Comment by daniehol** [comment]
Veldig bra forslag, @niirve! Liker det ^^,

**Comment by Dreamfreeze** [comment]
Slettes ikke dumt. Da er det enkelt å holde oversikten over hvor lenge man er i bomberom også.

**Comment by Mishapen** [comment]
Støtter forslaget @Niirve legger ut her.
