### ISSUE TITLE
Feil i pokeroppdraget

### ISSUE THREAD

**Issue by fre4k** [hswno/kofradia#24]
Hei!

 http://gyazo.com/222719afb9e710415ca5be568b899969
 Det bildet sier egentlig det meste.

Link til henvendelsen:
https://kofradia.no/support/?a=show&su_id=9837

----

https://kofradia.no/crewstuff/trac/ticket/598

**Comment by Dreamfreeze** [comment]
Finnes denne bugen fremdeles?

**Comment by Dreamfreeze** [comment]
http://puu.sh/lU0FM/448dfa7198.png
Ser ikke ut til å eksistere lenger.
