### ISSUE TITLE
Opprette broderskap i valgt konkurranse ved flere konkurranser

### ISSUE THREAD

**Issue by Dreamfreeze** [hswno/kofradia#240]
Usikker, men tror ikke dette er en bug som noen gang ble fikset. Hvis det er flere broderskapskonkurranser ute samtidig, vil man alltid opprette i den med minst tid igjen, uansett hvilken man faktisk velger å opprette i. Skulle det være en med én dag igjen, og en annen er tre dager igjen, så vil de som ønsker å delta i konkurranse miste mye tid uansett valg. Enten all tiden som allerede har passert på den første, eller en hel dag mindre hvis de venter til den første er fullført for å opprette i den andre.

Nå skal det sies at vi kan opprette og deaktivere konkurranser som vi vil, men det er ikke alltid det er den beste og riktige løsningen.

**Comment by Kuzat** [comment]
Jeg mener det bare burde være 1 aktiv konkurranse om gangen. Så jeg tror en bedre løsning vil være å begrense antall konkurranser til 1.

**Comment by actanon** [comment]
Med dagens aktivitet holder det med 1 aktiv konkurranse om gangen ja. Så ikke spillere bare oppretter en ny for å unngå konkurranse.

**Comment by Dreamfreeze** [comment]
Hva tenker dere i en situasjon etter restart og vi kanskje ønsker 3-4 etablerte broderskap? Vil vi fordele én konkurranse i uka eller starte to først og deretter to til eller overlappe dem noe? Jeg ser for meg at det kan bli noe taktisk. Noe vi uansett bør vurdere, er at spillere ikke kan opprette broderskap i en konkurranse og så legge ned umiddelbart som et forsøk på å ta opp en plass og sabbotere for andre.

**Comment by daniehol** [comment]
Å bare ha 1 broderskapskonkurranse om gangen, ser jeg ikke på som noe løsning.
Hva om man skulle ha flere konkurranser på et senere tidspunkt, da må man tilbake å fikse i koden hvis man bare tillater 1 konkurranse om gangen nå.

Så det skal være mulig å velge hvilken konkurranse man vil være med i. Er enig i siste kommentaren til @Dreamfreeze .
