### ISSUE TITLE
Ny spiller med samme spillernavn

### ISSUE THREAD

**Issue by Dreamfreeze** [hswno/kofradia#241]
Dersom en spiller dør eller deaktiverer seg, men fremdeles ønsker det samme spillernavnet på en ny spiller og samme bruker, er moderator+ nødt til å endre dette manuelt. Det skal i utgangspunktet være mulig for spillere å gjøre dette selv, så sant det er på samme bruker.

**Comment by daniehol** [comment]
Er ikke noe bug. Dette er i grunn tenkt til å være en slags pluss funksjon.
