### ISSUE TITLE
Små endringer i "Kriminalitet"

### ISSUE THREAD

**Issue by Curzer** [hswno/kofradia#263]
**Små endringer i "Kriminalitet"**

Er det mulig å få endret teksten på noen av kriminalitetene i spillet? 
Har laget en liten liste under på hva som kunne trengt en oppdatering. 

**Åssiden** 

-	Stjel en hest på Drammen travbane (Mulig legges ned) (eventuell endring "Stjel IT utstyr fra Åssiden Videregående Skole")
-	Ran Ica Maxi (Ica erstattes med Rema 1000)
-	Ran Kiwi (Kiwi XL)

**Gulskogen**

-	Ran Maxbo (Mulig erstattes med f.eks RSA BIL)

**Strømsø**

-	Ran Rimi (Coop Extra)

**Bragernes**

-	Ran Esso (Erstatt Esso med: Circkle K)

-Dersom crew ønsker bilder av flere steder som er nevnt i "krim" kan jeg være behjelpelig med dette ettersom at jeg bor i Drammen sentrum selv.

-Voyager

**Comment by Dreamfreeze** [comment]
Har snakket med @Curzer og fått ordnet på kriminalitetene. Bilder tenker jeg vi avventer eller tar etter hvert.
