### ISSUE TITLE
 Forslag til oppdrag

### ISSUE THREAD

**Issue by Curzer** [hswno/kofradia#264]
Hadde det vært en mulighet å dra inn «biltyveri» i oppdrag? 

Mitt forslag til oppdrag:
Deler inn oppdraget i 2 deler slik oppdrag er designet i dag slik at det ikke blir en endring der.
Oppdraget starter med å stjele 2 biler på rad. (Mulig denne kan økes) Når 2 biler er stjålet går man videre til nivå 2 på oppdraget.

Forslag til nivå 2 er veldig enkelt. Stjel mellom 5 – 10 biler (økes i forhold til rank?) og frakt deretter bilene til en annen bydel. Hvor bilene stjeles fra spiller ingen rolle, bilene sendes til et tilfeldig sted som blir generert i oppdraget f.eks jeg oppholder meg på Strøtvet og bilene skal sendes til Holmen.

Alle tall over er veiledende og kan endres/diskuteres om de skal endres eller ikke.

-Voyager

**Comment by Niirve** [comment]
Liker det! Gir litt mer variasjon mellom oppdragene dersom et nytt blir innført. Har du tenkt noe på belønningen for oppdraget?

**Comment by Dreamfreeze** [comment]
Det her er er veldig bra forslag, og jeg liker det godt! Derimot har vi issues inne som foreslår mer eller mindre nøyaktig det samme. Låser denne og viser til de andre issues. Ta heller saken der! :)

#74 
#192 
#215
