### ISSUE TITLE
Utbrytningsoppdraget

### ISSUE THREAD

**Issue by fre4k** [hswno/kofradia#28]
Fra SpeedL:
 Du har oppnådd 2 av 5 utbrytninger på rad. 1 minutt og 27 sekunder gjenstår
 Hele 3 stykker har vært i fengsel på denne tiden. Jeg synes oppdraget burde vært fjernet så lenge eller senket til det nivået som tilsvarer aktiviteten her inne. 5 stykker på 15 minutter er kun mulig på det mest aktive perioden av døgnet eller ved hjelp av venner. Ikke minst, når det faktisk er folk i fengsel, så er det flere som prøver på samme oppdrag. Er mer en irritasjon enn en utfordring.
https://kofradia.no/forum/topic?id=92797&replyid=1594370

 Han har et godt poeng.

----

https://kofradia.no/crewstuff/trac/ticket/599

Sjekk kommentarer på trac

**Comment by Dreamfreeze** [comment]
Fengselsoppdraget krever i dag 3 utbrytninger. Anser denne som løst.
