### ISSUE TITLE
Renter i firma/familie-banken

### ISSUE THREAD

**Issue by fre4k** [hswno/kofradia#29]
Jeg og andre i gjengen min, synes det hadde vært bra og hatt med renter i firmabankene også. Men er bare ett forslag ;)

 https://www.streetzmafia.net/support/index.php?a=show&su_id=8690

 Hva er meningene rundt dette? Skal vi f.eks. også gjøre slik at ff-banken blir som en vanlig spillerbank og må ha bankkonto hos et bankfirma?

---

https://kofradia.no/crewstuff/trac/ticket/239

Sjekk trac for kommentarer

**Comment by Dreamfreeze** [comment]
Usikker på hvordan det er tenkt at det skal funke, men tror ikke det er noen spesiell god idé uansett. Vil bli veldig mye penger i spillet og de som eier firma har allerede mulighet for å tjene penger på firmaet.

**Comment by actanon** [comment]
Neeeh. Forhåpentligvis kan vi fikse ting slik at firmaene kan tjene gode penger på andre måter. Så synes denne kan lukkes.
