### ISSUE TITLE
Ny blokkering: Poker

### ISSUE THREAD

**Issue by fre4k** [hswno/kofradia#31]
Det skjer stadig at man oppretter multibrukere for å spille seg opp, på poker. Hva med å gjøre så moderatorer+ kan blokkere for "pokerspilling?"

 Enten dette, eller så vi kan fjerne pengene spilleren har vunnet, for denne fortjenesten synes jeg ikke vedkommende skal få glede av.

 https://www.streetzmafia.net/min_side.php?u_id=22720&a=crew&b=blokk

---

https://kofradia.no/crewstuff/trac/ticket/429

**Comment by Dreamfreeze** [comment]
Litt usikker på hva som menes her. Hvordan spiller man seg opp med en multibruker? Sammenheng med hvordan pokeren fungerte i en periode, men ble endret? Snakk om såkalt teaming? Er denne utgått?

**Comment by actanon** [comment]
Bør heller løses med #144 etter min mening.

**Comment by DSivertsen** [comment]
@Dreamfreeze tror han mener at folk lager dobbel bruker for å fjerne sine "dårlig" poker runder, mens de lar de gode stå.

**Comment by Dreamfreeze** [comment]
I så fall mener jeg det er bedre om vi går for #144 som Anders sier. Unødvendig med en slik blokkering uansett, tenker jeg.
