### ISSUE TITLE
Visuell status på prestasjonene

### ISSUE THREAD

**Issue by fre4k** [hswno/kofradia#44]
Fjerne at en må holde over den grønne streken for å se hvor lagt en har kommet med prestasjonen. Og heller flytte det opp til hjørnet.

---

https://kofradia.no/crewstuff/trac/ticket/563

**Comment by Dreamfreeze** [comment]
Synes denne er veldig bra. Burde vel være enkel å få til?

**Comment by Kuzat** [comment]
Hvis jeg forstår denne rett så ønsker man å se progressen på en prestasjon uten å holde over den grønne streken.  [Her](https://github.com/hswno/kofradia/blob/master/app/pages/min_side_player.php#L720) er filen som trenger å endres. Da kan man f.eks lage et nytt p element som man legger til ac_data. Et lite eksempel hvordan det kan se ut.
![Visuell status på prestasjon eksempel](http://i.imgur.com/xkYKPnA.png)
Ville det funket?

**Comment by actanon** [comment]
Ja, det ser jo mye bedre ut.

**Comment by Kuzat** [comment]
Da skal det være implementert. #193
