### ISSUE TITLE
Mer lottostatistikk

### ISSUE THREAD

**Issue by fre4k** [hswno/kofradia#69]
Forslag fra DropsGFX - https://kofradia.no/support/index.php?a=show&su_id=9184

Hadde det vært mulig å fått en statistikk som viser hvor mye du har brukt på lottolodd, sammenlignet med hvor mye du har vunnet, så man ser om man har tapt eller tjent penger på lottoen?
Samt kanskje også vise hvor mange poeng man har vunnet? =)

Er dette noe vi synes høres ut som en god idé?

---

https://kofradia.no/crewstuff/trac/ticket/408

**Comment by Dreamfreeze** [comment]
Poeng hadde vært veldig interessant! Vi har allerede statistikk for hvor mye man har vunnet, så hvor mye man har brukt og forhold mellom disse synes jeg er lite interessant. Kunne vært interessant om lottoen ble gjort om til en funksjon hvor man var ute etter å tjene penger, men den brukes bare til å tjene poeng.

**Comment by Dreamfreeze** [comment]
Duplikat av #34
