### ISSUE TITLE
Utvide tidsrom ang. utkastelse av spillere fra bomberom

### ISSUE THREAD

**Issue by fre4k** [hswno/kofradia#70]
Hei!

 I dag er det slik at man kun kan kaste spillere ut av bomberommet sitt mellom 21 og 22. Jeg synes dette er et altfor lite tidsrom. Ettersom det er mulig å drepe 24/7, mener jeg det også bør være mulig å kaste ut spillere 24/7.

 Hva tenker dere om saken?

---

https://kofradia.no/crewstuff/trac/ticket/582

Sjekk trac for kommentarer

**Comment by Dreamfreeze** [comment]
Hele døgnet er NEI. Uansett er ikke angrepsfunksjonen døgnåpen lenger. Mener det bør være som det er. Andre tanker?

**Comment by Kuzat** [comment]
Enig med @Dreamfreeze, det burde være som det er nå
