### ISSUE TITLE
Oppdrag: Stjele 3 biler

### ISSUE THREAD

**Issue by fre4k** [hswno/kofradia#79]
Dette forslaget blir kanskje litt likt de andre, men stjele 3 biler fra same bydel.

---

https://kofradia.no/crewstuff/trac/ticket/473

**Comment by Dreamfreeze** [comment]
Se også: https://kofradia.no/forum/topic?id=93983

**Comment by Dreamfreeze** [comment]
Duplikat av #74

**Comment by Dreamfreeze** [comment]
Ja, se heller #74 og muligens #215
