### ISSUE TITLE
Kvitte seg med overflødige kuler (uten å miste dem)

### ISSUE THREAD

**Issue by fre4k** [hswno/kofradia#80]
Det er kjedelig å tape kulene sine etter oppdrag, fordi man har for mange. For eksempel, man har kapasitet på 10 kuler. Du har 5 fra før av og får 7 kuler til. Da vil 2 av kulene forsvinne.

 Hva synes dere om å gi spillere en bestemt tid på å kvitte seg med kulene? Enten ved å sette de inn i kulelager eller aukjonere bort. Det er kuler av fortjeneste som bare forsvinner.

---

https://kofradia.no/crewstuff/trac/ticket/590

Sjekk kommentarer på trac

**Comment by Dreamfreeze** [comment]
Synes ikke dette er noe vi trenger. Vi har en maksgrense av en grunn, så om man ikke klarer å holde orden på kulene sine, er det helt rett og rimelig at man ikke mottar de overflødige kulene.

**Comment by Dreamfreeze** [comment]
Etter å ha sett på trac, ser jeg at det var snakk om at overflødige kuler blir satt inn i broderskapet automatisk hvis det er plass. Tenker uansett nei. Glemmer man, så glemmer man, og da bør konsekvensene være deretter. Meninger?

**Comment by actanon** [comment]
Synes ikke denne hjelpen skal gis, egen feil hvis det skjer

**Comment by Mishapen** [comment]
Enig med dere begge over her; det fungerer fint som det er. Alle familier er jo stappfulle uansett, så det er ikke direkte mangel på kuler.

**Comment by Niirve** [comment]
Funker fint som det er nå.
