### ISSUE TITLE
Hendelse ved bud (auksjon)

### ISSUE THREAD

**Issue by fre4k** [hswno/kofradia#81]
Engiz31. januar 2012 16:50:24
 Mulighet at når noen byr på f.eks kuler på auksjonen, kunne det kommet en hendelse om det?

https://kofradia.no/support/?a=show&su_id=9821

---

https://kofradia.no/crewstuff/trac/ticket/592

**Comment by Dreamfreeze** [comment]
Auksjoner varer maks 30 minutter og man kan følge med på forsiden. Er dette nødvendig?

**Comment by Dreamfreeze** [comment]
Fremdeles enig med meg selv og tenker at dette ikke er nødvendig i det hele tatt. Derimot er det en bug med auksjoner som gjør at man ikke får hendelsen av vunnet auksjon før noen trykker inn på auksjon-siden. Her fikk jeg hendelsen klokken 06:31 fordi jeg trykket på siden "Auksjoner" akkurat da, men det står likevel at auksjonsslutt var 05:49: https://i.imgur.com/8vZSOI7.gifv
