### ISSUE TITLE
Nytt oppsett

### ISSUE THREAD

**Issue by fre4k** [hswno/kofradia#82]
Nå må du seriøst se over her. Når jeg var i klubben i går så gikk jeg innom å skulle sette meg inn i b-rom 48 timer i stede for 6 som jeg gjorde før jeg dro fra her. Logga meg på fra nedi der å gikk ut for å sette meg inn. Å fikk vær gang jeg prøvde å sette meg inn at det var "nytt oppsett". Kjørte nedi klubben gjennom Exsplorer da. Slike bugs jeg mener det bør gjøres no med. FØR man konsentrerer seg om nye ting man lager her inne.

https://kofradia.no/support/?a=show&su_id=9838

---

https://kofradia.no/crewstuff/trac/ticket/597

**Comment by Dreamfreeze** [comment]
Noen som skjønner denne?

**Comment by Kuzat** [comment]
Tror han snakker om når prisen forandrer seg og du må få nytt prisoppsett

**Comment by Dreamfreeze** [comment]
I så fall er det ingen bug og issuen kan lukkes. Ja?
