### ISSUE TITLE
Kanskje best å endre på poker oppdrag nu?

### ISSUE THREAD

**Issue by fre4k** [hswno/kofradia#84]
https://kofradia.no/support/?a=show&su_id=9859

 Av WatchTower:

 Hvordan kan dere forvente att noen skal klare dette oppdraget så vannskilegt som det er? Det er helt umuligt og få til flere ganger! Hvordan kan en som er ikke like aktive som meg pr dag få til dette oppdraget!? Hvordan kan dere forvente att aktiviteten på spillet blir bedre slik spillet er nå? Henrik, få i gang å jobb med feil i spillet med det samme! Dette er jo helt på tryne slikt ting har gått nå! Spillet her krever mer og mer sammenhold fra flere spillere for å klare ting, dette skal da ikke være slikt? Man skal ikke trenge 2-4personer får å få til et oppdrag!

---

https://kofradia.no/crewstuff/trac/ticket/601

Sjekk kommetarer på trac

**Comment by Dreamfreeze** [comment]
Er denne issuen noe vi trenger å forholde oss til lenger? Ærlig talt fungerer oppdraget fint, selv om det til tider kan være frustrerende og vanskelig. Nå har vi også nylig redusert antall spillere som kreves for del 1, og dessuten senket kravet på del 2.

**Comment by Niirve** [comment]
Skjønner frustrasjonen, men denne er ikke noe å forholde seg til lenger. Endringer er gjort så jeg anser den som avsluttet.
