### ISSUE TITLE
Lotto: Aktivitet, gevinst og rank!

### ISSUE THREAD

**Issue by fre4k** [hswno/kofradia#88]
Forslag fra forumet: 

 Det er ikke vits i å ta utgangspunkt i lottoen for 15 personer når det aldri er 15 personer som spiller lotto. Det burde vert slik at de som vinner i lotto får mer penger og poeng, men at loddene er dyrere. 

https://kofradia.no/forum/topic?id=93091&replyid=1602734

---

 Hva med å gjøre en liten vri nå som spillet er lite aktivt?

---

https://kofradia.no/crewstuff/trac/ticket/618

**Comment by Dreamfreeze** [comment]
Lottoen tar nå utgangspunkt i 5 spillere. Ideelt sett burde det trolig være 15 ved høyere aktivtet, men er dyrere lottolodd noe vi kunne vurdert nå? I tillegg kan vi vurdere å gjøre lottoen til en pengefunksjon ved å endre gevinsten for hver plass og hvor mye som går ut av spillet. Poeng bør fjernes, mener jeg. Likevel kan jeg gå med på å øke maks poeng til 750, men skulle mye heller sett den redusert til 500.

**Comment by actanon** [comment]
Fjerne poeng fra lotto ja, det var interessant. Mer en pengefunksjon ja, hmmm... Jeg støtter i hvert fall å øke prisen på lottolodd, det går inn i den totale verdiendringen på mange funksjoner som jeg ser for meg.

**Comment by Mishapen** [comment]
Spør du meg er lottofunksjonen den viktigste, og raskeste måten å sanke poeng på. Jeg ønsker veldig gjerne å beholde poengene, men stiller meg per nå uten preferanse på hvorvidt poeng-gevinsten skal øke eller minke.

Å øke prisen på lodd hadde vært veldig interessant, noe jeg gjerne kan stille meg bak. Men hvor høyt har jeg heller ikke per nå en formening om.

**Comment by DSivertsen** [comment]
Nei, nei og nei. Hvorfor skal dere fjerne eller endre en funksjon som fungerer? Lotto funksjonen vil aldri klare å konkurrere med poker når det kommer til penger. Aldri. Om dere vil fjerne poeng fra lottoen kan dere fjerne hele lotto funksjonen når dere først er i gang.

**Comment by Dreamfreeze** [comment]
@DSivertsen Jeg mener iallfall at lotto skal handle om penger. Om ikke bare penger, så iallfall mer om penger enn poeng. Poker er et helt annet spill med en helt annen risikofaktor, og hele poenget mitt er at spillere skal ha andre muligheter for penger i fremtiden når det er andre rankefunksjoner å by på. Det er ikke alle som liker å spille poker, og spillet blir lite dynamisk hvis det skal være den eneste og beste måten å skaffe seg penger på. Spillet i sin helhet er mangelfullt på funksjoner akkurat nå, men om vi skal tenke fremover, er dette noe vi bør ta opp og gjøre oss opp noen tanker om, tenker jeg. Merk også at det jeg kommer med bare er et forslag i denne saken. Det dreier seg vel faktisk om spillets integritet, og på forumet er det en tråd som forhåpentligvis gir forslaget litt bedre sammenheng.

**Comment by DSivertsen** [comment]
@Dreamfreeze Ja, men per dags dato så burde dere ikke tukle med lotto, frem til noe nytt som kan gjøre ranking bedre. Ved det så må dere justere rankene. Det er for lett å bli Don om jeg kan gjøre det på tre uker som jeg har bevist før, vet også Tande har gjort det i rekordfart. Men per dags dato så gir ikke lottoen noe fordel ved en seier annet enn usle 500 poeng, som også kan ses på i lengden som mye om man holder på. Akkurat nå med denne aktiviteten så kan lottoen fungere som en slags "påloggings grunn" for å få med seg de få poengene, ser ikke for meg at milliarderene gjør det samme for noen få "millioner"

**Comment by Dreamfreeze** [comment]
@DSivertsen Du har nok rett i en del av det du sier. Kanskje er det faktisk jeg som er for tidlig ute med å bringe dette opp. Jeg vil derimot på ingen måte si at det er for lett å bli Don. Om du bruker tre uker fra Ubetydelig til Don, så har du brukt veldig mye tid på Kofradia. Men om vi skulle si at det er for lett å bli Don, hva mener du bør justeres med rankene? Og hvorfor er ikke redusering av poeng på lottoen en mulig løsning til akkurat det?

**Comment by DSivertsen** [comment]
@Dreamfreeze Tja, jeg ville ha likt om det var vanskeligere generelt. Flere poeng for å nå Don. I perspektiv når flere av spillerene, og den tiden jeg var aktiv som mest så hadde jeg ranka don 3-4 ganger etter å allerede blitt Don. Der hjalp jo selvfølgelig bonus statusene som legende etc. 

Lottoen burde ikke reduseres, eller endres per dags dato fordi det ikke finnes noen bedre alternativer.

**Comment by Dreamfreeze** [comment]
@DSivertsen Jeg ser hva du mener. Riktig nok er det å ranke til Don flere ganger etter å ha blitt Don første gang betydelig mye raskere. Oppdrag er jo også en stor faktor. Jeg tenker at justering av rankene er noe vi må vurdere å endre på når vi har fått på plass en del andre ting.

**Comment by DSivertsen** [comment]
@Dreamfreeze Ja, det er jo klart. Nå rotet jeg meg kanskje litt bort fra topic'et, men håper du forstod hvor jeg ville. Kommer det inn flere ranke muligheter i spillet som f.eks organisert krim. Flere oppdrag eller nye metoder (som hadde vært kjempe spennende å få inn) så ville det selvfølgelig vært naturlig å vurdere å fjerne poeng fra lottoen, men per dags dato så gir det, som sagt; En bitter liten grunn til å logge inn på hver halvtime.
