### ISSUE TITLE
Bug i ranking etter oppdrag!

### ISSUE THREAD

**Issue by fre4k** [hswno/kofradia#89]
Traxon forklarer følgende:

 Hei. I går gjorde jeg fengselsutbrytningsoppdraget og gikk over 300% i rankstatus blant de beste rankerne de siste dagene. Så rett etter det gjorde jeg rankingoppdraget og jeg datt plutselig ned til litt over 30% der. Jeg kom heller ikke blant de top 10 beste rankerne de siste 24 timene, som jeg synes er litt rart. Har dere en forklaring til det ?

 Henvendelse: https://kofradia.no/support/?a=show&su_id=9958

---

https://kofradia.no/crewstuff/trac/ticket/619

**Comment by Dreamfreeze** [comment]
https://kofradia.no/min_side?up_id=41073&a=log&side=122 (9. september 2012)
Her ser man at det er lottoprestasjonen som har fullført oppdraget. Dette er samme bug som #13, #161, #162 og #175. Angående rankstatus er det nok en kombiasjon av denne buggen og at noen andre fikk mengder med poeng i samme tidsrom som fører til at han har 30 % og ikke får rankbonus.
