### ISSUE TITLE
Endring av profilbilde i crewloggen

### ISSUE THREAD

**Issue by fre4k** [hswno/kofradia#92]
Jeg mener alt bemerkelig som man gjør innenfor crew burde havne i loggen, for oversikt. Pr i dag er det ingen som får med seg hvis moderator+ forandrer noen sitt profilbilde.

---

https://kofradia.no/crewstuff/trac/ticket/623

**Comment by Dreamfreeze** [comment]
Også forummoderator kan så vidt jeg vet endre på avatar (og profiler?), men de kan ikke laste opp nye bilder.

**Comment by Niirve** [comment]
Forummoderator kan ikke endre profiler, bare se de. De kan endre avatar til et spilleren allerede har lastet opp, eller standard. 

Men ja, dette burde dukke opp i loggen.
