### ISSUE TITLE
Oppdrag: Angripe spiller med høy rank

### ISSUE THREAD

**Issue by fre4k** [hswno/kofradia#96]
Fra Headblower
https://kofradia.no/crewstuff/trac/ticket/445#comment:2

 Angripe en spiller med x2 høyere rank enn deg selv.

 Premie: Rank.

---

https://kofradia.no/crewstuff/trac/ticket/467

**Comment by Dreamfreeze** [comment]
Synes denne inngår i #75 og #125, og de to er mye enklere å bygge videre på enn denne.
